### ISSUE TITLE
When open google maps, the starting point address is not informed

### ISSUE THREAD

**Issue by djalmaaraujo** [includable/react-native-map-link#10]
Is that expected? Is it possible to have the FROM address too, and not only the destiny address?

**Comment by tschoffelen** [comment]
That is indeed the intended behaviour in this library, which currently only focusses on displaying a certain location in a maps app of the user’s choosing.

It is however possible to open up the directions view in Google Maps with both a start and end point, have a look at Google’s documentation: https://developers.google.com/maps/documentation/urls/ios-urlscheme#display_directions

**Comment by djalmaaraujo** [comment]
@tschoffelen Would your be able to accept a pr with this feature? I found that apple also supports `saddr`.

https://developer.apple.com/library/content/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html

**Comment by tschoffelen** [comment]
@djalmaaraujo Yes, I'd love to see a PR that implements this, as long as it does not change the basic behaviour of the library when a starting address is not defined.

Thanks in advance!

**Comment by djalmaaraujo** [comment]
@tschoffelen Let's see how it goes, I need this for a project, so I think I will take a look.
