### ISSUE TITLE
Google Maps shows title as unnamed location 

### ISSUE THREAD

**Issue by wellingtonblessed** [includable/react-native-map-link#13]
I'm trying it out and adding the title with the name of the place but in Google maps it shows as unnamed location, yet if I open using Uber it works well.

**Comment by tschoffelen** [comment]
Please see this issue comment: https://github.com/includable/react-native-map-link/issues/2#comment-361992831

This is not a bug in this library, but unfortunately simply the way Google Maps works (it ignores your location name and used its own).
