### ISSUE TITLE
Open map for directions with "to" and "from" address populated

### ISSUE THREAD

**Issue by Noitidart** [includable/react-native-map-link#16]
Thanks for this awesome module! I needed to pop open the map with the to/from address populated. Is this possible? (if geolocation is disabled i was planning on leaving the from blank so they can fill it in)

**Comment by tschoffelen** [comment]
Have you tried adding the `sourceLatitude` & `sourceLongitude` parameters (see readme). They act more or less as a From address. 

Does that cover your use case?

**Comment by Noitidart** [comment]
Ah thank you I missed that! I didn't try it but it sounds like it does. Thanks very much!
