### ISSUE TITLE
Integration request: Bolt

### ISSUE THREAD

**Issue by ahdam** [includable/react-native-map-link#161]
This is a feature request, not a bug.
Although this module is awesome, integration with Bolt would make it even more so :)

**Comment by tschoffelen** [comment]
Do you know if Bolt has any documentation available on their URL scheme?

**Comment by vvscode** [comment]
Bolt has some deeplinking schema (at least for ios), but it's not ready to be presented as public api

**Comment by olfway** [comment]
@vvscode May be it's now ready? at lease for open bolt with destination
