### ISSUE TITLE
Passing  sourceLatitude/sourceLongitude as undefined breaks the path

### ISSUE THREAD

**Issue by vvscode** [includable/react-native-map-link#173]
At the https://github.com/flexible-agency/react-native-map-link/blob/master/src/index.js#L42

we verify if params are in the options, but do not check the value, so for `undefined` we have

```
parseFloat(undefined); // NaN
``` 

for sure it can be fixed in the client code, but seems like nice to handle it inside the lib

![image](https://user-images.githubusercontent.com/6904368/113116399-14277c80-9216-11eb-9cb9-8b78d656de94.png)

**Comment by vvscode** [comment]
@theneekz  PR is welcome

**Comment by theneekz** [comment]
[pr submitted](https://github.com/flexible-agency/react-native-map-link/pull/201/files)

**Comment by tschoffelen** [comment]
This has been fixed since.
