### ISSUE TITLE
Any clue why Google Maps doesn't show in the list of apps?

### ISSUE THREAD

**Issue by ryross** [includable/react-native-map-link#18]
I'm using `react-native-map-link` 1.1.1 with CRNA and testing using the Expo Client on my iPhone 7 plus on 11.3. I definitely have Google Maps installed but it doesn't show up in the `askAppChoice()` list. Any clue why?

**Comment by tschoffelen** [comment]
Yes, I’m pretty sure that has to do with Apple’s limitation where apps can only open other apps if they are specified in the Info.plist file. [See the README of this library for more info](https://github.com/includable/react-native-map-link/blob/master/README.md#a-note-about-ios-9).

So I think you might have to [eject](https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md) your Expo app for this to work. Not a limitation of this library, but a limitation of iOS.

**Comment by ryross** [comment]
Wow, you would have hoped I read the readme... lol. I totally skipped that section because I read it as just being for iOS9. Thanks!
