### ISSUE TITLE
 add Sygic map 

### ISSUE THREAD

**Issue by mohammed-sec2010** [includable/react-native-map-link#198]
Hi
add this Sygic GPS Navigation & Offline Maps app please to be supported

**Comment by tschoffelen** [comment]
Happy to accept PRs for this, or have a look myself if I happen to find some time in the next few weeks. Do you know if there's documentation available on the URL scheme for this application?

**Comment by m4tt86** [comment]
> Happy to accept PRs for this, or have a look myself if I happen to find some time in the next few weeks. Do you know if there's documentation available on the URL scheme for this application?

Hello, the sygic deep link is: com.sygic.aura://

**Comment by tschoffelen** [comment]
I haven't found time to implement this, and probably won't for the next couple of weeks/months, but still happy to accept a PR for this!

**Comment by tschoffelen** [comment]
Implemented in #281
