### ISSUE TITLE
Enable point in GoogleMaps

### ISSUE THREAD

**Issue by fgarzonhz** [includable/react-native-map-link#199]
At this moment, the library can do route between 2 points, very good. However in some times we need only a point in GMaps, so if you can enable the possibility to send as parameter if we hope to do a route or only paint a point from coordinates.

Thanks.

**Comment by theneekz** [comment]
[see my patch](https://github.com/flexible-agency/react-native-map-link/issues/200#issue-1010135195)

**Comment by tschoffelen** [comment]
This has been resolved
