### ISSUE TITLE
Pass an address as a parameter instead of a long-lat parameters

### ISSUE THREAD

**Issue by MedRaid** [includable/react-native-map-link#210]
can we passe an adresse as a paramater instead of a long-lat parameters ?

**Comment by stevenmathers** [comment]
Hi, can we bump this?

Often users enter 'almost' addresses without accepting auto-matched suggestions, meaning we dont have lat/lng available, even though the entered text is sufficient for maps to work out where it is.  

This is a pretty important quality of life option

**Comment by trevorrd** [comment]
Has any thought or effort gone into this? It started almost 2 years ago! Without being able to pass the address, this library is pretty useless unless you have the latitude and longitude coordinates.

**Comment by tschoffelen** [comment]
It's definitely not a use case I personally have, because I want to send users to a specific location rather than doing a search, but I can understand why that would be useful.

I'm still happy to accept a PR for that functionality if you'd like to add it!

**Comment by trevorrd** [comment]
I've created a PR for this new functionality. I would love to have others check out the changes, test it out, etc... then if we look good, let's merge it into master! 

https://github.com/includable/react-native-map-link/pull/272

**Comment by tschoffelen** [comment]
Closing as fixed - addressed in #272, with a fix pending in #293
