### ISSUE TITLE
Apple Maps Navigation bar is not updating when direction starts

### ISSUE THREAD

**Issue by crzycoder** [includable/react-native-map-link#227]
`showLocation({`
       ` latitude: sourceLat,`
    ` longitude: sourceLng,`
        `sourceLatitude: lat,`
        `sourceLongitude: lng,`
        `alwaysIncludeGoogle: true,`
       ` dialogTitle: 'Open map',`
        `dialogMessage: 'What app would you like to use?',`
        cancelText: 'Cancel',
        `appsWhiteList: ['google-maps', 'apple-maps'],`
        `directionsMode: 'car'`
   ` })`
   
   User is moving but Navigation blue bar is not updating like google maps do. 

https://user-images.githubusercontent.com/43851308/178799292-dfdd13e2-0aae-4fb4-b705-0329574c53de.mp4

**Comment by tschoffelen** [comment]
I'm not sure I understand what you mean. This package has no influence on how the Maps UI is displayed.

**Comment by crzycoder** [comment]
@tschoffelen forget the package just use apple maps for direction. when you move blue bar is also updating according to which direction you are moving. but when I use this library for direction the user maker is updating but blue bar is not updating .
