### ISSUE TITLE
Apple Maps doesn't pick Street Number from Latitude and Longitude

### ISSUE THREAD

**Issue by jpate148** [includable/react-native-map-link#23]
* Google Maps and Waze working as expected but Apple Maps doesn't pick street number, It just picks Street Name, City, State and Postal Code

**Comment by tschoffelen** [comment]
This is related to the way in which Apple Maps reverse geocoding (lat,lng -> address) works, but I don't think this has actually anything to do with this library itself.

**Comment by jpate148** [comment]
@tschoffelen Thanks for responding so quickly, I just try adding `address` param to `apple-maps` url and it worked. If I pass title in address param, it works as expected. 

E.g. `&address=${encodedTitle}`, which makes `title` a required field to work with apple maps. I am still testing it but if it works, Do you want me to send PR for it?

**Comment by tschoffelen** [comment]
Have a look at #5, maybe you would be able to build this in right away. Would love to see a PR for that!

**Comment by jpate148** [comment]
Thanks @tschoffelen I'll take a look at it in this weekend.

**Comment by tschoffelen** [comment]
Closing this one in favour of #5, which basically proposed the same changes.
