### ISSUE TITLE
Missing callback type in Popup component

### ISSUE THREAD

**Issue by TacticCoder** [includable/react-native-map-link#235]
While trying to implement the 'onAppPressed' callback i notice that the pressed app name indeed return from the first function parameter, but in the TS definition seems to be incorrect.

Current:
`onAppPressed: () => void;`

Need to be:
`onAppPressed: (appName: MapId) => void;`

**Comment by tschoffelen** [comment]
Good point! Feel free to open a PR to fix the type refs.

**Comment by TacticCoder** [comment]
@tschoffelen 
Done:
https://github.com/includable/react-native-map-link/pull/236
