### ISSUE TITLE
Release update after 2.7.15 is missing

### ISSUE THREAD

**Issue by asurion-ashutosh** [includable/react-native-map-link#237]
https://github.com/includable/react-native-map-link/releases
- above page is not updated with latest versions. is there any other place where i can see change log for 2.8 and above versions.

**Comment by tschoffelen** [comment]
Sorry, would you mind explaining what you mean?

**Comment by EmmanuelSkapple** [comment]
this package still works for Expo?

**Comment by tschoffelen** [comment]
@asurion-ashutosh Good point, we haven't actively been tracking this using Github releases, but it might be good to add a changelog to the README. This package is very simple though, so hopefully the list of recent commits should contain most of the info you need.

**Comment by tschoffelen** [comment]
@EmmanuelSkapple This is a bit off-topic, but yes it should, please see the Expo related instructions in the README & open a new issue if those aren't working for you.
