### ISSUE TITLE
Warning message is being shown after coming back to the app. [Unable to open url ....]

### ISSUE THREAD

**Issue by Saad-Bashar** [includable/react-native-map-link#240]
Hi, thanks a lot for your work on this! Recently after updating our react native app to 0.67.5 we are getting a warning message. Even though react-native-map-link seems to work fine but after coming back to the app, the app throws out a warning message. Please check the following preview. 

https://user-images.githubusercontent.com/13269141/208821528-224d0fb3-8ab6-4773-b8fd-2d123afddabf.mov

**Comment by tschoffelen** [comment]
I think this might be react-native related, not directly related to this library. I wonder if you're seeing the same if you're invoking this directly:

```
Linking.openURL('maps://...')
```
