### ISSUE TITLE
yandex maps is not available

### ISSUE THREAD

**Issue by castusoft** [includable/react-native-map-link#247]
Yandex maps option is not showing up in expo app,
here is what I have:
```app.json
...
"ios": {
      "supportsTablet": true,
      "infoPlist": {
        "LSApplicationQueriesSchemes": [
          "comgooglemaps",
          "yandex",
          "yandex-taxi",
          "yandex-maps",
          "waze"
        ]
      }
    },
...
```
it looks like `canOpenUrl` for yandex maps returns false, even though app is installed...

**Comment by tschoffelen** [comment]
I think the URL scheme for Yandex.Maps is `yandexmaps`, without the dash
