### ISSUE TITLE
App icon images are circles instead of original design

### ISSUE THREAD

**Issue by mattaningram** [includable/react-native-map-link#251]
I want to display the relevant app icons the way they appear in iOS and Android (or at least with as little assumed shape as possible), but the icons provided by `react-native-map-link` are all circles making the icons look wrong and cropped.

Ideally these images would be un-cropped rectangles and the user can decide to put them in circle crops if needed.

**Comment by mattaningram** [comment]
Probably what I'll do. I just think it makes sense that if the package does provide app icons they should be as default as possible so that you can then modify them to your specific needs. It's easy to make a square icon into a cropped circle, but you can't uncrop an already pre-cropped icon into the original square. Less work for you when you add new icons, and easier for package users to make it work for their needs.

**Comment by tschoffelen** [comment]
That makes a lot of sense. I'm not particularly attached to the rounded style, so happy to accept a PR to replace them as well. In that case, we'd just have to release it as a new major version, in case people aren't expecting the style change.

**Comment by tschoffelen** [comment]
I'm going to close this for now, but if there's still appetite to change these, I'm happy to accept a PR!
