### ISSUE TITLE
Logo design proposal: React Native Map Link

### ISSUE THREAD

**Issue by baranpirincal** [includable/react-native-map-link#26]
Hey! I can contribute on your project with making logo design. If you interested I can show my portfolio. I am waiting your feedback, have a nice day!

Best Regards
Baran Pirinçal
Graphic Designer

**Comment by tschoffelen** [comment]
Sure, feel free to add a proposal!

**Comment by baranpirincal** [comment]
Hey again @tschoffelen . I made a logo design as I said and want to show you. I hope you like it! 

![react native map](https://user-images.githubusercontent.com/37786733/41008304-0070c76e-6933-11e8-9ccc-8d13a1b7d6b6.jpg)

**Comment by baranpirincal** [comment]
@tschoffelen I will do some arrangements, I am waiting your feedback! Have a nice day! :)

**Comment by tschoffelen** [comment]
I like your idea, and appreciate the effort, but think that something much more simple would be better (flat logomark in a single colour).

**Comment by baranpirincal** [comment]
Hey again! I made again according to your feedbacks. If you don't like or want to more simple design I will make it again :) Have a nice day!

![zxc](https://user-images.githubusercontent.com/37786733/41188735-d5400b14-6bca-11e8-99d1-8394f46ab2e7.jpg)

**Comment by tschoffelen** [comment]
Thanks for your suggestions, but @ahsanfazal has already implemented another logo:


![banner](https://user-images.githubusercontent.com/666220/41202196-d0c519e8-6cc5-11e8-9963-4299222c50f2.png)
