### ISSUE TITLE
apple maps does not start navigation in turn by turn mode, rather it shows 'top down' navigation

### ISSUE THREAD

**Issue by stefoid** [includable/react-native-map-link#260]
when I go to apple maps it always shows 'top down' view of navigation, initially.

if you then cancel navigation, then restart it by pressing GO, it shows 'point of view' navigation instead, which users prefer

is there some parameter or way to force apple maps to use the preferred view when initating navigation from react-native-map-link?

thanks!

**Comment by stevenmathers** [comment]
actually, after some testing, Ive found the answer - if you supply sourceLatitude/longtitude,   apple will NOT use turn by turn navigation.  Omit these and it does.
