### ISSUE TITLE
Biking Directions Mode not working on Apple Maps

### ISSUE THREAD

**Issue by collinmyers** [includable/react-native-map-link#266]
~~I am currently integrating this into a project of mine, I am have a way that lets the user save their preference on the kind of directions they would like to receive when directed to their navigation app. For some reason the biking directions in Apple maps dont work and it defaults back to driving. All other navigation modes work fine in Apple maps and there are no issues with Google Maps getting biking directions.~~ Edit: Sorry I just seen in the documentation below. I tried looking prior, but must have missed it. But is there any particular reason why the directions mode bike will not work for Apple Maps.

**Comment by tschoffelen** [comment]
I think this might be something that the Apple Maps URL scheme just doesn't (yet) support possibly - it's not mentioned in the docs here:

https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html

If you do find a way to make it work, please feel free to submit a PR, would love to add that to the library!
