### ISSUE TITLE
ShowLocationProps type export missing in v3

### ISSUE THREAD

**Issue by bhandanyan-nomad** [includable/react-native-map-link#276]
Previously, you could get the options for `showLocation` from the package:
```javascript
import { Options, showLocation } from 'react-native-map-link';
```

It looks like Options has been renamed and is no longer exported.

**Comment by bhandanyan-nomad** [comment]
Tried to import `ShowLocationProps` and `MapLinkOptions` - neither are properly exported

**Comment by tschoffelen** [comment]
Thanks for flagging this! Would you be able to put in a PR to export this type?

Also related to #275 - which is about another type that should ideally be exported

**Comment by bhandanyan-nomad** [comment]
Which of the two types I mentioned should be exported?

**Comment by bhandanyan-nomad** [comment]
@tschoffelen please review https://github.com/includable/react-native-map-link/pull/277 it will export a type that will resolve this issue
