### ISSUE TITLE
Popup component is not exported

### ISSUE THREAD

**Issue by LeCiel** [includable/react-native-map-link#278]
Hello,
I installed 3.0.2, and tried import Popup component, but my IDE says 
```Module '"react-native-map-link"' has no exported member 'Popup'.```

It exports `PopupProps` and `PopupStyleProp`, but there was no `Popup`. Is it intended?

**Comment by HectorUbiera** [comment]
i am having the same issue, any update?

**Comment by oxidia** [comment]
I am having the same issue
version: 3.0.2
