### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by mbifulco** [includable/react-native-map-link#28]
Hi there - it would be very helpful if there were a changelog for this package.  In particular, knowing if there are breaking changes between v1.X.x and v2.0.x would be great!

**Comment by tschoffelen** [comment]
Great point. Do you have a standard format that you’d like to see?

Also, to answer your last question: V2 adds the <Popup> component, but does not break the existing V1 behaviour.

**Comment by mbifulco** [comment]
Generally changelogs seem to come in two formats on github, from what I've seen.  `react-router` is an example of a repo that does a pretty good job:

- They have a  CHANGELOG.md file [in the repo](https://github.com/ReactTraining/react-router/blob/master/CHANGES.md)
- and more or less the same content on their [releases page](https://github.com/ReactTraining/react-router/releases)

Either/both of those would be great!

**Comment by tschoffelen** [comment]
Cool, yes, let's make sure to create a CHANGELOG.md the next time we do a release, and keep it updated from then. Also, feel free if one of you have some time to create a CHANGELOG.md based on the recent commits.

**Comment by tschoffelen** [comment]
Started using the [Release notes](https://github.com/includable/react-native-map-link/releases) in Github to keep a changelog.

Closing this issue.
