### ISSUE TITLE
`googlePlaceId` no longer exists in version 3 

### ISSUE THREAD

**Issue by andreialecu** [includable/react-native-map-link#282]
Updated an app from v2 to v3 and it appears that the property `googlePlaceId` which was part of the `Options` interface as it was passed to `<Popup options={...}` no longer exists.

Seems like an oversight?

**Comment by tschoffelen** [comment]
That might be an error in the Typescript definition, because I think it should still be accepted. Happy to accept a PR for this!

**Comment by meteorlxy** [comment]
This issue would also be fixed by #286
