### ISSUE TITLE
Applications filtering

### ISSUE THREAD

**Issue by gbahamondezc** [includable/react-native-map-link#29]
Hi, 

First, thanks a lot for this awesome work!

I was taking a look  to the docs and code and i can't find a way to show only the apps that i want in the Popup Component.

**IE:** Maybe i have google maps installed  but i don't want to show Google Maps as an option.

Is that possible?

Regards

**Comment by johanleroch** [comment]
Hi,

> IE: Maybe i have google maps installed but i don't want to show Google Maps as an option. Is that possible?

Yes it's possible, we can add an option allowing to blacklist apps on demand. 
Atm the popup shows all the applications installed on the phone. You'll find below the list of concerned apps:
- Apple Maps
- Google Maps
- Citymapper
- Uber
- Lyft
- The Transit App
- Waze
- Yandex.Navi
- Moovit

@tschoffelen: What do you think about that feature?

Regards,

**Comment by gbahamondezc** [comment]
@johanleroch I can help with a PR if you find this feature useful.

**Comment by tschoffelen** [comment]
Blacklist would be nice, but wouldn't it be better to make it a whitelist? I think that's more in tune with how that feature would be used in most situations.

**Comment by gbahamondezc** [comment]
@tschoffelen  agree, whitelist make more sense than a blacklist.

**Comment by johanleroch** [comment]
@tschoffelen: Sure, whitelist will make more sense.
@gbahamondezc: You're welcome if you want to make a PR

**Comment by gbahamondezc** [comment]
Ok, 

If really makes sense for you guys,  i will do between today and next Monday.

Thanks !

**Comment by gbahamondezc** [comment]
Was implemented in #30  , thanks!
