### ISSUE TITLE
Android - Latitude and longitude is getting ignored

### ISSUE THREAD

**Issue by Maxwell2022** [includable/react-native-map-link#3]
Doesn't seems to pickup the `latitude` and `longitude` on Android

It opens the google map with `Location` as a search keyword.

If we specify a `title` then Google map is opening searching for this title, however still no pin corresponding to the latitude and longitude.

It's working fine on iOS

**Comment by Maxwell2022** [comment]
new format for google search is: `https://maps.google.com/?q=-33.871473,151.205739`

From what I can see, you cannot specify additional search string

**Comment by tschoffelen** [comment]
Closing this to continue discussion in PR #4.
