### ISSUE TITLE
not working on expo 51

### ISSUE THREAD

**Issue by fozzarelo** [includable/react-native-map-link#300]
I migrated from expo 50 to 51 and the feature stopped working. No errors or warnings displayed.

- getApps returns an empty array
- showLocation doesn't do anything

have you tested it with sdk51?

thank you for the great library.

**Comment by NataliiaYakorieva** [comment]
Hi, I have a similar issue, however, it's only reproducible on Android, and on iOS it works fine.

After some digging, I figured out, that `Linking.canOpenURL` returns false on Android (from both `react-native` or `expo-linking`). I tried it out with the following URL: https://www.google.com/maps/. 

`Linking.canOpenURL` from `react-native` is called in `isAppInstalled` util, which is eventually called by `showLocation`.

Related dependencies versions:
"expo-linking": "~6.2.2",
"expo": "~50.0.19",
"react-native": "0.73.6",
"react-native-map-link": "2.7.25"

Please let me know if you have any ideas of the issue's root cause and thank you for the library!

**Comment by dani-z** [comment]
@fozzarelo I am running latest expo 51.0.24 and works perfectly fine for me.

**Comment by tschoffelen** [comment]
Hi @fozzarelo! Sorry to hear you're having problems getting the library to work.

Some pointers that might help:

- Have you added the [Expo plugin](https://github.com/tschoffelen/react-native-map-link/blob/master/docs/expo.md) and re-built your native app?
- Are you testing on a device that has one or more supported map apps installed? The simulator usually doesn't work for this.

**Comment by markaustinws** [comment]
I'm also experiencing issues with this.  getApps for me is only returning Google maps.  I have Waze installed too.  However, to launch, I have to specify that I want to use Waze.  By default it always launches Google Maps.  Runnin Expo GO on my tablet.  Would I need a build to pick up the rest?

I have read that the way in which default apps on Android 12+ has changed.

I don't really want to implement a Map App chooser and just use the one that's been configured by default on the device

**Comment by tschoffelen** [comment]
Hi @markaustinws - this is the expected behaviour on Expo Go - the Expo Go app isn't whitelisted to query existence of other apps on the system. Only native builds with the [Expo plugin](https://github.com/tschoffelen/react-native-map-link/blob/master/docs/expo.md) installed will allow you to do this.

**Comment by markaustinws** [comment]
Hi @tschoffelen Thanks for confirming.  Great library! :)

**Comment by markaustinws** [comment]
I've created a preview iOS build.  Uploaded to Browser Stack, but when attempting to launch, I'm getting the following errors:
Aug 23 16:10:58 WSCrewDev(UIKitCore)[4616] <Error>: Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")Aug 23 16:11:55 WSCrewDev(Network)[4616] <Error>: nw_read_request_report [C1] Receive failed with error "Software caused connection abort"Aug 23 16:13:27 WSCrewDev(CoreLocation)[4616] <Fault>: This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.Aug 23 16:13:27 WSCrewDev(libCoreFSCache.dylib)[4616] <Error>: fopen failed for data file: errno = 2 (No such file or directory)Aug 23 16:13:27 WSCrewDev(libCoreFSCache.dylib)[4616] <Error>: Errors found! Invalidating cache...Aug 23 16:14:12 WSCrewDev(libsystem_containermanager.dylib)[4616] <Error>: container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitledAug 23 16:14:12 WSCrewDev(libsystem_containermanager.dylib)[4616] <Error>: container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitledAug 23 16:14:12 WSCrewDev(libsystem_containermanager.dylib)[4616] <Error>: container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitledAug 23 16:14:12 WSCrewDev(libsystem_containermanager.dylib)[4616] <Error>: container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitledAug 23 16:14:12 WSCrewDev(libsystem_containermanager.dylib)[4616] <Error>: container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitledAug 23 16:14:13 WSCrewDev(libsystem_containermanager.dylib)[4616] <Error>: container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitledAug 23 16:15:50 WSCrewDev(CFNetwork)[4616] <Error>: Received XPC error Connection interrupted for message type 3 kCFNetworkAgentXPCMessageTypePACQueryAug 23 16:15:50 WSCrewDev(CFNetwork)[4616] <Error>: Received XPC error Connection invalid for message type 3 kCFNetworkAgentXPCMessageTypePACQueryAug 23 16:19:29 WSCrewDev(CFNetwork)[4616] <Error>: Received XPC error Connection interrupted for message type 3 kCFNetworkAgentXPCMessageTypePACQueryAug 23 16:19:29 WSCrewDev(CFNetwork)[4616] <Error>: Received XPC error Connection invalid for message type 3 kCFNetworkAgentXPCMessageTypePACQuery

**Comment by tschoffelen** [comment]
None of these messages seem to be related to this library as far as I can tell @markaustinws

**Comment by mrevanzak** [comment]
its working on me. make sure to run `expo prebuild --clean` and rebuild the development apps

**Comment by markaustinws** [comment]
Hi @mrevanzak - Thanks.  Last day before leave and I didn't realise that BrowserStack doesn't preload with any map applications.  Installed Google Maps and now working.

**Comment by tschoffelen** [comment]
Looks like this can be closed for now - feel free to re-open if it's still a problem!
