### ISSUE TITLE
Update react-native-modal

### ISSUE THREAD

**Issue by anonrig** [includable/react-native-map-link#32]
With Babel 7 on 0.56.0 react-native-modal which is a dependency of this package, fails to build. So we need to update react-native-modal to latest version.

The quickfix for react-native-modal is in this commit: https://github.com/react-native-community/react-native-modal/commit/e2618cbd771d1488d61197de7e0cafd2d95138e9

The task of the issue of react-native-modal can be found in this issue: https://github.com/facebook/react-native/issues/20038

Best,
Y

**Comment by tschoffelen** [comment]
Has been fixed in NPM version 2.0.5, which depends on `react-native-modal@^6.4.0`.
