### ISSUE TITLE
Add support for Grab app

### ISSUE THREAD

**Issue by pjay79** [includable/react-native-map-link#38]
Great package. Can you add support for Grab? www.grab.com

**Comment by tschoffelen** [comment]
I can’t find anything related to the Grab app on that documentation site. How are Here and Grab related?

**Comment by tschoffelen** [comment]
Closing this for now, since I haven't received any information about the URL scheme of the Grab app.

If you really want this feature, please open a new issue with more specific information about the Graph app URL scheme.
