### ISSUE TITLE
ActionSheet Not Opening in IOS

### ISSUE THREAD

**Issue by mohanraj546** [includable/react-native-map-link#43]
Hi,

ActionSheet not opening in ios.
When I debug the code I found that Linking.canOpenUrl() method returns false but the apps are installed in mobile(ios) and defined the schemas in LSApplicationQueriesSchmes. Please can you give me the suggestion how to do?

Thanks in Advance

**Comment by tschoffelen** [comment]
Did you re-build the native app after changing Info.plist?

**Comment by mohanraj546** [comment]
Yes

**Comment by mohanraj546** [comment]
In android its working fine But in ios not getting the actionSheet because canOpenURL method returns false for the installed apps

**Comment by tschoffelen** [comment]
Can you send me your full Info.plist file (thomas@includable.com). That’s the only possible thing that can be wrong, I think.

**Comment by mohanraj546** [comment]
sent the Info.plist in mail. Please check let me know is there any issues with it

**Comment by maxencehenneron** [comment]
not sure if related but you wrote : "LSApplicationQueriesSchmes" it should be "LSApplicationQueriesSchemes"

**Comment by tschoffelen** [comment]
I think this is indeed a problem with the configuration of your React Native/Xcode project, since I haven't heard other people mention having this issue.

Going to close this for now, feel free to re-open or comment if anyone is still experiencing this problem.
