### ISSUE TITLE
"Require cycle" warning in the app (RN 0.57)

### ISSUE THREAD

**Issue by zubko** [includable/react-native-map-link#47]
After updating to React Native 0.57 there is a warning about require cycle:

<img width="487" alt="screen shot 2018-10-19 at 5 29 08 pm" src="https://user-images.githubusercontent.com/16039/47224640-acbe3f00-d3c4-11e8-8a62-46566226d16d.png">

I can add this warning to warning ignores as a workaround.

**Comment by tschoffelen** [comment]
Indeed not really a best practice. Feel free to submit a PR for this if you find the time!

**Comment by tschoffelen** [comment]
I haven't yet had a chance to test this on RN 0.57 myself net, but ca864d6 should resolve this warning.

Once I get a chance to test it on a device I'll release a new version to NPM.
