### ISSUE TITLE
Revisited: opening with google maps on Android opening system's popup to choose with which app to open

### ISSUE THREAD

**Issue by Rommero** [includable/react-native-map-link#49]
This issue is an extension/proposal for https://github.com/includable/react-native-map-link/issues/37

After a deeper investigation I found out that system's popup shows only when the map url is `https://maps.google.com/...` . If we use `https://www.google.com/maps/dir/` it's still recognized with google maps yet not recognized by third-party apps which eliminates that annoying popup. 

Can you make deeper config options/googlemap-specific option to solve this issue? (or I can submit a PR with it) @tschoffelen

**Comment by tschoffelen** [comment]
Thanks for this research! I've applied the change of the Google URL in version 2.1.2.
