### ISSUE TITLE
Issue with fork and PR

### ISSUE THREAD

**Issue by rollsroyc3** [includable/react-native-map-link#55]
I created a fork and am testing the fix on my repo but the directory format is different than yours when I add it to my project. I noticed you have a src file in the repo but when I add it to my project the src becomes the root. But in my fork when I try to add it to my project its still react-native-map-link/src.

Any help on what I am doing wrong? I didnt see any scripts in package.json..

**Comment by tschoffelen** [comment]
Make sure you're using the `index.js` file in the root directory as well, the `src` directory is not actually the access point of the package.
