### ISSUE TITLE
Uber isn't workin here

### ISSUE THREAD

**Issue by PedroRique** [includable/react-native-map-link#7]
Google Maps an Waze working Fine, but when Uber is the choice just open the app.

Expected Behavior:
Open Uber and fill the input with the adress, just leaving to the user the final step.

**Comment by tschoffelen** [comment]
Thanks for the bug report. 

I won't be able to test/fix this myself for the next week or so, so if you need to have this fixed before then, I would encourage you to have a look at the [Uber docs](https://developer.uber.com/docs/riders/ride-requests/tutorials/deep-links/introduction#standard-deep-links) and submit a PR, which I will then merge as soon as possible!
